In [1]:
!pip freeze

alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
asn1crypto==1.0.1
astroid==2.3.1
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.2.0
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.0
bitarray==1.0.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.3.4
boto==2.49.0
Bottleneck==1.2.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
clyent==1.2.2
colorama==0.4.1
comtypes==1.1.7
conda==4.7.12
conda-build==3.18.9
conda-package-handling==1.6.0
conda-verify==3.4.2
contextlib2==0.6.0
cryptography==2.7
cycler==0.10.0
Cython==0.29.13
cytoolz==0.10.0
dask==2.5.2
decorator==4.4.0
defusedxml==0.6.0
distributed==2.5.2
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
fsspec==0.5.2
future==0.17.1
gevent==1.4.0
glob2==0.7
greenlet==0.4.15
h5py==2.9.0

In [4]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [4]:
a = np.array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [6]:
a = np.array([[1, 2, 3], [1, 2, 3]])

In [7]:
print(a)

[[1 2 3]
 [1 2 3]]


In [8]:
print(a[0])
print(a[0:2])

[1 2 3]
[[1 2 3]
 [1 2 3]]


In [9]:
print(a[0:3])

[[1 2 3]
 [1 2 3]]


In [10]:
print(np.dtype(np.int32))
print(np.dtype('i4'))

int32
int32


In [11]:
dt = np.dtype([('age', np.int8)])
print(np.array([(10,), (20, ), (30, )], dtype=dt))

[(10,) (20,) (30,)]


In [12]:
a = np.array([(10,),(20,),(30,)], dtype=dt) 
print(a['age'])
type(a)

[10 20 30]


numpy.ndarray

In [13]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [14]:
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype=student)
print(a)
print(a['marks'])

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[50. 75.]


In [15]:
# more than 20 letters in str
a = np.array([('abcsssssssssssssssssssssssssssssssssssssssssssssssssssssssss', 21, 50), ('xyz', 18, 75)], dtype=student)
print(a)

[(b'abcsssssssssssssssss', 21, 50.) (b'xyz', 18, 75.)]


In [29]:
a = np.array([[1, 2, 3, 4], [4, 5, 6]])
print(a.shape)
print(a.ndim)
a.shape = (3, 2)
print(a)

(2,)
1


ValueError: cannot reshape array of size 2 into shape (3,2)

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [25]:
a = np.arange(24)
print(a)
print(a.ndim)
print(a.shape)

b = a.reshape(2, 4, 3)
print(b)
print(b.ndim)
print(b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3
(2, 4, 3)


In [30]:
x = np.array([1, 2, 3, 4])
x.itemsize

4

In [31]:
x = np.array([1, 2, 3, 4, 5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [33]:
x = np.empty([3, 2], dtype=int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [35]:
x = np.zeros((2, 3), dtype=int)
print(x)

[[0 0 0]
 [0 0 0]]


In [37]:
x = np.ones((5,), dtype=int)
print(x)

[1 1 1 1 1]


In [39]:
x = [1, 2, 3]
a = np.asarray(x)
print(a)
a[0] = 5
print(a)
print(x)

[1 2 3]
[5 2 3]
[1, 2, 3]


In [43]:
s = 'Hello world'
a = np.fromiter(s, dtype='S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


In [3]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [6]:
x = np.arange(5, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [8]:
x = np.arange(10, 20, 2.2, dtype=float)
print(x)

[10.  12.2 14.4 16.6 18.8]


In [11]:
x = np.linspace(10, 20, 25)
print(x)

[10.         10.41666667 10.83333333 11.25       11.66666667 12.08333333
 12.5        12.91666667 13.33333333 13.75       14.16666667 14.58333333
 15.         15.41666667 15.83333333 16.25       16.66666667 17.08333333
 17.5        17.91666667 18.33333333 18.75       19.16666667 19.58333333
 20.        ]


In [12]:
x = np.logspace(1, 2, num=10)
print(x)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [29]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)
print(a[1:3])
print(a[0])
print(a[::2])
print(a[...,0])
x = a[1:3]
x[0] = [0, 0, 0]
print(x)
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]
[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 4]
[[0 0 0]
 [4 5 6]]
[[1 2 3]
 [0 0 0]
 [4 5 6]]


In [30]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


In [34]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(x)

rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols]
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2]
 [ 9 11]]


In [35]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(x[1:4,1:3])
print(x[1:4,[1,2]])

[[ 4  5]
 [ 7  8]
 [10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [38]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

print(x[x > 5])

[ 6  7  8  9 10 11]


In [40]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [42]:
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [9]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array is:')
print(a)
print('\n')

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2 * x
print('Modified array is:')
print(a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
